// <auto-generated />
namespace Shop.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class price_datatype_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(price_datatype_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201611052232309_price_datatype_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
