// <auto-generated />
namespace Shop.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bool_not_mapped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bool_not_mapped));
        
        string IMigrationMetadata.Id
        {
            get { return "201610172101402_bool_not_mapped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
